# Официальный Node.js образ в качестве базового
FROM node:16-alpine as build

# Рабочую директорию внутри контейнера
WORKDIR /app

# Копирование package.json и package-lock.json в рабочую директорию
COPY package*.json ./

# Зависимости
RUN npm install

# Копирование всего проекта в рабочую директорию
COPY . .

# Сборка React приложение
RUN npm run build

# Создание новый контейнер для nginx
FROM nginx:stable-alpine

# Копирование собранных файлов из предыдущего контейнера в директорию nginx
COPY --from=build /app/build /usr/share/nginx/html

# Копирование конфигурационного файла nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Открытие порта 80 для доступа к приложению
EXPOSE 80

# Запуск nginx
CMD ["nginx", "-g", "daemon off;"]